### ISSUE TITLE
what command line do I execute?

### ISSUE THREAD

**Issue by ghost** [dorkster/flare-starter-pack#1]
In order to execute this pack, what command line (on bash etc.) do I execute?
In the first place, Do I need a command line?

**Comment by dorkster** [comment]
No command line needed. Just copy the `flare-starter-pack` directory from the `mods/` directory to the `mods/` directory for Flare. Then you can enable the mod in the Configuration menu. The `flare-starter-pack` is intended to be used by itself, so disable other mods like `fantasycore` and `alpha_demo`.

![screenshot_2017-11-20_10-56-35](https://user-images.githubusercontent.com/913982/33027588-80f2a710-cde1-11e7-8c68-179181c89d09.png)
